export { default as About } from "./about/About";
export { default as Company } from "./company/Company";
export { default as Contacts } from "./contacts/Contacts";
export { default as Faqs } from "./faqs/Faqs";
export { default as Footer } from "./footer/Footer";
export { default as Header } from "./header/Header";
export { default as Navbar } from "./navbar/Navbar";
export { default as Reviews } from "./reviews/Reviews";
export { default as Services } from "./services/Services";
